<?php

/**
 * @file
 * Functions to support theming.
 */

/**
 * Implements hook_preprocess_image_widget().
 */
function cheeta_theme_preprocess_image_widget(array &$variables) {
  $data = &$variables['data'];

  // This prevents image widget templates from rendering preview container HTML
  // to users that do not have permission to access these previews.
  // @todo revisit in https://drupal.org/node/953034
  // @todo revisit in https://drupal.org/node/3114318
  if (isset($data['preview']['#access']) && $data['preview']['#access'] === FALSE) {
    unset($data['preview']);
  }
}

function cheeta_theme_preprocess_paragraph(&$variables) {
  if ($variables['paragraph']->bundle() === 'image_and_text_component') {
    $boolean_field = $variables['paragraph']->get('field_image_alignment')->value;
    $variables['text_position'] = (bool) $boolean_field;
  }
}
